service:
  name: acme-silverpop-nightly-sync

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs8.10

functions:
  acmeNightlySync:
    handler: handler.acmeNightlySync
    events:
      - http:
          method: get
          path: acmeNightlySync
