service:
  name: AcmeNightlySync

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs8.10
  profile: cjativa-acme-nightly-sync
  

functions:
  index:
    handler: handler.index
    timeout: 300
    memorySize: 3008
    events:

      # Scheduled event for the Sales Report
      - schedule:
          name: AcmeNightlySync-ScheduledEvent-SalesReportExecution
          description: 'An event scheduled to run at midnight of each week day at 4 AM UTC | 12 AM UTC-4'
          rate: cron(0 5 * * ? *)
          enabled: true
          input:
            report: Sales
            reportId: SalesReport

      # Scheduled event for the Transactions Report
      - schedule:
          name: AcmeNightlySync-ScheduledEvent-TransactionsReportExecution
          description: 'An event scheduled to run at midnight of each week day at 4:01 AM UTC | 12:01 AM UTC-4'
          rate: cron(1 5 * * ? *)
          enabled: true
          input: 
            report: Transactions
            reportId: TransactionsReport

      # Scheduled event for the Memberships Report
      - schedule:
          name: AcmeNightlySync-ScheduledEvent-MembershipsReportExecution
          description: 'An event scheduled to run at midnight of each week day at 4:02 AM UTC | 12:02 AM UTC-4'
          rate: cron(2 5 * * ? *)
          enabled: true
          input:
            report: Memberships
            reportId: MembershipsReport

      # Scheduled event for the Persons Report
      - schedule:
          name: AcmeNightlySync-ScheduledEvent-ContactsReportExecution
          description: 'An event scheduled to run at midnight of each week day at 4:03 AM UTC | 12:03 AM UTC-4'
          rate: cron(3 5 * * ? *)
          enabled: true
          input:
            report: Contacts
            reportId: ContactsReport