service:
  name: AcmeNightlySync

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs8.10
  profile: cjativa-acme-nightly-sync

functions:
  index:
    handler: handler.index