interface Transaction {

    AccountName: string, 
    AccountCategoryName: string, 
    TransactionAmount: string, 
    DiscountedTransactionAmount: string, 
    DiscountTransactionValue: string, 
    SaleChannel: string, 
    OrderItemType: string, 
    ItemName: string, 
    CouponCode: string, 
    CouponName: string, 
    EventName: string, 
    EventStartTime: string, 
    TicketType: string, 
    AddOn: string, 
    Quantity: string, 
    DiscountedUnitPrice: string, 
    PaymentAmount: string, 
    Email: string, 
    EventTemplateCustomField2: string, 
    TransactionId: string, 
    OrderNumber: string, 
    CheckInStatus: string,
    ConversionStatus: string,
    TransactionItemId: string, 
    TransactionDate: string,
}

export { Transaction };