enum TransactionReportFieldIndices {

    OrganizationName = 0,
    OrganizationCategoryName = 1,
    TransactionAmount = 2,
    DiscountedTransactionAmount = 3,
    DiscountTransactionValue = 4,
    SaleChannel = 5,
    OrderItemType = 6,
    ItemName = 7,
    CouponCode = 8,
    CouponName = 9,
    EventName = 10,
    EventStartTime = 11,
    TicketType = 12,
    AddOn = 13,
    Quantity = 14,
    DiscountedUnitPrice = 15,
    PaymentAmount = 16,
    Email = 17,
    ContactFirstName = 18,
    ContactLastName = 19,
    ZipCode = 20,
    MembershipExternalId = 21,
    MembershipPrimaryFirstName = 22,
    MembershipPrimaryLastName = 23,
    MembershipLevelName = 24,
    MembershipOfferingName = 25,
    EventTemplateCustomField2 = 26,
    TransactionId = 27,
    OrderNumber = 28,
    TransactionItemId = 29,
    TransactionDate = 30,
}

export { TransactionReportFieldIndices }